package edu.mum.cs.cs525.labs.exercises.lab04.solution;
import java.awt.*;
import java.awt.event.*;
import javax.swing.*;

public class JFrame1 extends javax.swing.JFrame
{
	NameFactory nfactory = new NameFactory();
	public JFrame1()
	{
		// This code is automatically generated by Visual Cafe when you add
		// components to the visual environment. It instantiates and initializes
		// the components. To modify the code, only use code syntax that matches
		// what Visual Cafe can generate, or Visual Cafe may be unable to back
		// parse your Java file into its visual environment.
		//{{INIT_CONTROLS
		setTitle("JFC Application");
		setDefaultCloseOperation(javax.swing.JFrame.DO_NOTHING_ON_CLOSE);
		getContentPane().setLayout(null);
		setSize(464,260);
		setVisible(false);
		JLabel1.setText("Name");
		getContentPane().add(JLabel1);
		JLabel1.setBounds(84,36,48,40);
		getContentPane().add(JTextFieldName);
		JTextFieldName.setBounds(144,36,238,30);
		JLabel2.setText("First");
		getContentPane().add(JLabel2);
		JLabel2.setBounds(84,144,48,40);
		getContentPane().add(JTextFieldFirst);
		JTextFieldFirst.setBounds(144,144,238,30);
		JLabel3.setText("Last");
		getContentPane().add(JLabel3);
		JLabel3.setBounds(84,180,48,40);
		getContentPane().add(JTextFieldLast);
		JTextFieldLast.setBounds(144,180,238,30);
		JButtonProccess.setText("Proccess");
		getContentPane().add(JButtonProccess);
		JButtonProccess.setBounds(168,84,167,32);
		//}}

		//{{INIT_MENUS
		//}}

		//{{REGISTER_LISTENERS
		SymWindow aSymWindow = new SymWindow();
		this.addWindowListener(aSymWindow);
		SymAction lSymAction = new SymAction();
		JButtonProccess.addActionListener(lSymAction);
		//}}
	}

	
	public static  void main(String args[])
	{
		try {
		    try {
		        UIManager.setLookAndFeel(UIManager.getSystemLookAndFeelClassName());
		    } 
		    catch (Exception e) { 
		    }

			//Create a new instance of our application's frame, and make it visible.
			(new JFrame1()).setVisible(true);
		} 
		catch (Throwable t) {
			t.printStackTrace();
			//Ensure the application exits with an error condition.
			System.exit(1);
		}
	}


	//{{DECLARE_CONTROLS
	javax.swing.JLabel JLabel1 = new javax.swing.JLabel();
	javax.swing.JTextField JTextFieldName = new javax.swing.JTextField();
	javax.swing.JLabel JLabel2 = new javax.swing.JLabel();
	javax.swing.JTextField JTextFieldFirst = new javax.swing.JTextField();
	javax.swing.JLabel JLabel3 = new javax.swing.JLabel();
	javax.swing.JTextField JTextFieldLast = new javax.swing.JTextField();
	javax.swing.JButton JButtonProccess = new javax.swing.JButton();
	//}}

	//{{DECLARE_MENUS
	//}}

	void exitApplication()
	{
		try {
		    	this.setVisible(false);    // hide the Frame
		    	this.dispose();            // free the system resources
		    	System.exit(0);            // close the application
		} catch (Exception e) {
		}
	}

	class SymWindow extends java.awt.event.WindowAdapter
	{
		public void windowClosing(java.awt.event.WindowEvent event)
		{
			Object object = event.getSource();
			if (object == JFrame1.this)
				JFrame1_windowClosing(event);
		}
	}

	void JFrame1_windowClosing(java.awt.event.WindowEvent event)
	{
		// to do: code goes here.
			 
		JFrame1_windowClosing_Interaction1(event);
	}

	void JFrame1_windowClosing_Interaction1(java.awt.event.WindowEvent event) {
		try {
			this.exitApplication();
		} catch (Exception e) {
		}
	}

	class SymAction implements java.awt.event.ActionListener
	{
		public void actionPerformed(java.awt.event.ActionEvent event)
		{
			Object object = event.getSource();
			if (object == JButtonProccess)
				JButtonProccess_actionPerformed(event);
			
		}
	}

	void JButtonProccess_actionPerformed(java.awt.event.ActionEvent event)
	{
		String name=JTextFieldName.getText();
		Namer namer=nfactory.getNamer(name);
		JTextFieldFirst.setText(namer.getFirst()); 
		JTextFieldLast.setText(namer.getLast()); 
	}
}
